# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Musings by robweber
email: your-email@example.co
description: >- # this means to ignore newlines until "baseurl:"
  Some random musings about code projects created and contributed to on GitHub.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robweber.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  robweber

# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
  - jekyll-paginate

# list of syntax highlight options: https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers
kramdown:
  syntax_highlighter: rouge
  auto_ids:       true
  toc_levels:     1..3

permalink: /:categories/:title/
excerpt_separator: <!--more-->

# read time estimation
read_time: true
words_per_minute: 200

# pagination settings
paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
